<?php
  $passages = [
    0 => 'the battle of, leipzig',
    1 => 'consider that Harry unleashes his magic by uttering the right incantation Of course discovering and applying these incantations are no simple matters',
    2 => 'When the Declaration of Independence was read with all its flaming radical language from the town hall balcony in Boston it was by Thomas Craftsx a member of the Loyal Nine group',
    3 => 'All of the characters in Animal farm have counterparts in real life. This book was based on the Russian Revolution, and all the important populace of the revolution are symbolized. Some of the animals represent individuals in the Russian Revolution, and some types of animals represent different types of Russian citizens. The book carries out much like the actual revolution.',
    4 => 'Maybe there is a flaw in the photo industry itself? Is today\'s model of licensing and sales of photographs viable? How best to sell your photos? Will open resources photo stocks increase supply growth up until the number of pictures will not reach a level where photographers could not even very cheap to sell good photos and make money on those that sell? Theoretically, this horrible scenario is likely to become reality. Already Shutter stock alone offers more than 5 million photographs, which do not require payment of royalties, and, as stated CEO John Orangey, each month the number of new revenue in the millions. Number of images in the bank Dreamtime also exceeded 5 million. Due to the fact that the old photos  sold or not  remain in their bases, photo stock will continue to grow indefinitely. Since the proposal ahead of demand  in the world has always been more pictures than buyers  prices will become lower and lower.',
    5 => 'Lauded as the “food of the gods” (Theobroma) by the Swedish botanist Carl Linnaeus in 1753, the cacao plant (Theobroma cacao) has always elicited a certain amount of scientific curiosity and mystical reverence from Europeans. Tucked away under the canopy within the planet’s narrow equatorial zone, the only environment in which it grows, and first cultivated in the lands that now constitute Guatemala and Belize, cacao had spent centuries well hidden from Continental eyes.'
  ];
  // 0 => 'the battle of, leipzig or battle of the nations. was fought from the sixteenth to nineteenth of october at taco city',
